name: Test GCP Auth
on:
  workflow_dispatch:
jobs:
  test-auth:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/144447625768/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "144447625768-compute@developer.gserviceaccount.com"
      
      - name: Verify Authentication
        run: |
          gcloud auth list
