name: Deploy Dog
on:
  workflow_dispatch:
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2
      
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/144447625768/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "144447625768-compute@developer.gserviceaccount.com"
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: devops-team-14-863342
          install_components: 'run'
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy game-server-service \
            --port 8080 \
            --source . \
            --region=europe-west6 \
            --allow-unauthenticated
      
      - name: Get service URL
        run: |
          SERVICE_URL=$(gcloud run services describe game-server-service \
            --platform=managed \
            --region=europe-west6 \
            --format='value(status.url)')
          echo "Service is running at: $SERVICE_URL"
